site_name: Cyber compass tool
site_description: Documentation for Cyber compass tool
site_author: Andrea Skytterholm
copyright: 2025 All Rights Reserved by the NEMECYS Consortium

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

docs_dir: docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
